baseURL = "http://skarmjakten.fi/"
languageCode = "sv"
defaultContentLanguage = "sv"
title = "Sk√§rmjakten"
staticDir = ["resultat", "static"]

assetDir = "src"



[params]
  background_color_class = "bg-blue"

  github_username = "skarmjakten"
  top_graphic = "purmo"

  time_format_RFC3339 = "2006-01-02T15:04:05Z07:00"
  time_format_RFC822 = "Mon, 02 Jan 2006 15:04:05 -0700"
  time_format_default = "Jan 2, 2006"
